project:
  type: website
  output-dir: docs
  resources:
    - "*.wav"
    - "*.csl"

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

# Metadata stuff
pagetitle: "Tobias Stephan"
author-meta: "Tobias Stephan"

website:
  title: "Tobias Stephan"
  description: "Tobias Stephan is a postdoc and lecturer at Lakehead University, researching lithospheric deformation and teaching data structural geology & tectonics."
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer:
    left: |
       <span class="faux-block">Tobias Stephan (he/him)</span>
       <span class="faux-block">[<img class="manImg" src="pictures/ORCID_iD.png" alt="ORCID" style="height:15px"></img> 0000-0002-9290-014X](https://orcid.org/0000-0002-9290-014X)</span>
    center: "Lakehead University respectfully acknowledges its campuses are located on the traditional lands of Fort William First Nation, Signatory to the Robinson Superior Treaty of 1850 and the Ojibwe, Odawa, and Pottawatomi nations, collectively known as the Three Fires Confederacy."
    right: |
       <span class="faux-block">Made with [<img class="manImg" src="pictures/Rlogo.png" alt="R" style="height:15px"></img>](https://posit.co/download/rstudio-desktop/?cmplz-force-reload=1732239687111) and [<img class="manImg" src="pictures/logo-quarto2.png" alt="Quarto" style="height:15px"></img>](https://quarto.org/)</span>
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - research/index.qmd
      - publications.qmd
      - software.qmd
      - teaching.qmd
      - href: cv/cv.pdf
        text: "Curriculum Vitæ"
        icon: file-pdf-fill

format:
  html:
    theme: [cosmo, styles.scss]
    page-layout: full
    #grid:
    #  body-width: 900px
    #toc: false
    #code-link: true
    #anchor-sections: true
    #fig-cap-location: margin
    #reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
