---
title: Publications
---

- **Stephan, T.**, Phillips, N., Tiitto, H., Perez, A., Nwakanma, M., and Hollings, P. (2025) "Going with the flow - Changes of Vorticity Controls Gold Enrichment in Archean Shear Zones (Shebandowan Greenstone Belt, Superior Province, Canada)". *Journal of Structural Geology*. doi: [10.1016/j.jsg.2025.105542](https://doi.org/10.1016/j.jsg.2025.105542)

- **Stephan, T.**, and Enkelmann, E. (accepted) "All Aligned on the Western Front of North America? Analyzing the Stress Field in the Northern Cordillera". *Tectonics*. doi: [10.1029/2025TC009014](https://doi.org/10.1029/2025TC009014)

-   Padgett, J., Enkelmann, E., Kellett, D., Moynihan, D., and **Stephan, T.** (2025) "Cenozoic faulting in the Upper Hyland River Valley, Southeastern Yukon: A thermochronological perspective". *Canadian Journal of Earth Sciences* 62(5): 1002-1022. doi: [10.1139/cjes-2024-0147](https://doi.org/10.1139/cjes-2024-0147) \| [citation](publications/Padgett2025_CJES.bib) \| [<i class="bi bi-file-pdf-fill"></i>](publications/Padgett2025_CJES.pdf)

-   Schaeben, H., Kroner, U., and **Stephan, T.** (2024): "Mathematical Fundamentals of Spherical Kinematics of Plate Tectonics in Terms of Quaternions". *Mathematical Models and Methods in Applied Sciences* 47(6): 4469-4496. doi: [10.1002/mma.9823](https://doi.org/10.1002/mma.9823) \| [citation](publications/Schaeben2024_MMAS.bib) \| [<i class="bi bi-file-pdf-fill"></i>](publications/Schaeben2024_MMAS.pdf)

-   **Stephan, T.**, Enkelmann, E., and Kroner, U. (2023): "Analyzing the horizontal orientation of the crustal stress adjacent to plate boundaries". *Scientific Reports* 13:15590. doi: [10.1038/s41598-023-42433-2](https://doi.org/10.1038/s41598-023-42433-2) \| [citation](publications/Stephan2023_SciRep.bib) \| [<i class="bi bi-file-pdf-fill"></i>](publications/Stephan2023_SciRep.pdf)

-   Járóka, T., Pfänder, J. A., Seifert, T., Hauff, F., Sperner, B., Staude, S., **Stephan, T.**, and Schulz, B. (2023): "Age and petrogenesis of Ni-Cu-(PGE) sulfide-bearing gabbroic intrusions in the Lausitz Block, northern Bohemian Massif (Germany/Czech Republic)". *Lithos* 444-445:107090. doi: [10.1016/j.lithos.2023.107090](https://doi.org/10.1016/j.lithos.2023.107090) \| [citation](publications/Jaroka2023_LITHOS.bib)

-   Kroner, U., Romer, R. L., and **Stephan, T.** (2023): "Die Rekonstruktion von relativen Plattenbewegungen aus dem paläozoischen Deformationsmuster der kontinentalen Kruste". *Zeitschrift der Deutschen Gesellschaft für Geowissenschaften (J. Appl. Reg. Geol.)*. doi: [10.1127/zdgg/2023/0365](https://doi.org/10.1127/zdgg/2023/0365) \| [citation](publications/Kroner2023_ZDGG.bib)

-   Köhler, S., Duschl, F., Fazlikhani, H., Koehn, D., **Stephan, T.**, and Stollhofen, H. (2022): "Reconstruction of cyclic Mesozoic-Cenozoic stress development in SE Germany using fault-slip and stylolite inversion". *Geological Magazine* 159 (11–12): 2323-2345. doi: [10.1017/S0016756822000656](https://doi.org/10.1017/S0016756822000656) \| [citation](publications/Koehler2022_GeoMag.bib)  \| [<i class="bi bi-file-pdf-fill"></i>](publications/Koehler2022_GeoMag.pdf)

-   Kroner, U., **Stephan, T.**, and Romer, R. L. (2022): "Paleozoic orogenies and relative plate motions at the sutures of the Iapetus-Rheic Ocean". In Y. D. Kuiper, J. B. Murphy, R. D. Nance, R. A. Strachan, and M. D. Thompson (Eds.), New Developments in the Appalachian-Caledonian-Variscan Orogen. *Geological Society of America*. doi: [10.1130/2021.2554(01)](https://doi.org/10.1130/2021.2554(01)) \| [citation](publications/Kroner2022_GSA.bib)

-   Schaeben, H., Kroner, U., and **Stephan, T.** (2021): "Euler Poles of Tectonic Plates". In B. S. Daza Sagar, Q. Cheng, J. McKinley, and F. Agterberg (Eds.), *Encyclopedia of Mathematical Geosciences. Encyclopedia of Earth Sciences Series*. doi: [10.1007/978-3-030-26050-7_435-1](https://doi.org/10.1007/978-3-030-26050-7_435-1) \| [citation](publications/Schaeben2022_Springer.bib)

-   Caracciolo, L., Ravidà, D. C. G., Chew, D., Janßen, M., Lünsdorf, N. K., Heins, W. A., **Stephan, T.**, and Stollhofen, H. (2021): "Reconstructing environmental signals across the Permian-Triassic boundary in the SE Germanic Basin: A Quantitative Provenance Analysis (QPA) approach". *Global and Planetary Change*, 206:103631. doi: [10.1016/j.gloplacha.2021.103631](https://doi.org/10.1016/j.gloplacha.2021.103631) \| [citation](publications/Carraciolo2021_GPC.bib)

-   Kroner, U., **Stephan, T.**, Romer, R. L., and Roscher, M. (2020): "Paleozoic plate kinematics during the Pannotia–Pangaea supercontinent cycle". *Geological Society, London, Special Publications* 503, SP503-2020-15. doi: [10.1144/SP503-2020-15](https://doi.org/10.1144/SP503-2020-15) \| [citation](publications/Kroner2020_GS.bib)

-   **Stephan, T.**, Kroner, U., Romer, R. L., and Rösel, D. (2019): "From a bipartite Gondwana shelf to the arcuate Variscan belt: The Early Paleozoic evolution of northern Peri-Gondwana". *Earth-Science Reviews* 192: 491–512. doi: [10.1016/j.earscirev.2019.03.012](https://doi.org/10.1016/j.earscirev.2019.03.012) \| [citation](publications/Stephan2019_ESR.bib)

-   Heinicke, J., **Stephan, T.**, Alexandrakis, C., Buske, S., and Gaupp, R. (2019): "Alteration as possible cause for transition from brittle failure to aseismic slip: the case of the NW-Bohemia / Vogtland earthquake swarm region". *Journal of Geodynamics* 124: 79–92. doi: [10.1016/j.jog.2019.01.010](https://doi.org/10.1016/j.jog.2019.01.010) \| [citation](publications/Heinicke2019_JG.bib)

-   **Stephan, T.**, Kroner, U., and Romer, R. L. (2018): "The pre-orogenic detrital zircon record of the Peri-Gondwanan crust". *Geological Magazine* 156(2): 281–307. doi: [10.1017/s0016756818000031](https://doi.org/10.1017/s0016756818000031) \| [citation](publications/Stephan2019_GeolMag.bib)

-   **Stephan, T.**, Kroner, U., Hahn, T., Hallas, P., and Heuse, T. (2016): "Fold / cleavage relationships as indicator for late Variscan sinistral transpression at the Rheno-Hercynian – Saxo-Thuringian boundary zone, Central European Variscides". *Tectonophysics* 681: 250–262. doi: [10.1016/j.tecto.2016.03.005](https://doi.org/10.1016/j.tecto.2016.03.005) \| [citation](publications/Stephan2016_TECTONO.bib)
