---
title: Teaching
---

#### Lead Instructor

-   **Geological Case Studies** [(Lakehead University, GEOL 4313)]{style="color:grey"} \| [Syllabus <i class="bi bi-file-pdf-fill"></i>](teaching/GEOL4313_Syllabus_2026.pdf)

-   **Structural Geology and Tectonics** <span style="color:grey">(Lakehead University, GEOL 3310) \| [Syllabus <i class="bi bi-file-pdf-fill"></i>](teaching/GEOL3310_Syllabus_2026.pdf)

-   **Metamorphic Petrology** <span style="color:grey">(Lakehead University, GEOL 3217) \| [Syllabus <i class="bi bi-file-pdf-fill"></i>](teaching/GEOL3217_Syllabus_2026.pdf)

#### Teaching Assistant

-   **3D Modeling** [(Technische Universität Bergakademie Freiberg, 2018)]{style="color:grey"}

#### Short-Courses and Workshops

-   **Plate motion and deformation of the lithosphere** [(workshop in 2023/10 at Department of Geology, Technische Universität Bergakademie Freiberg, Germany)]{style="color:grey"}

-   **Programming with R — A Beginners’ Guide for Geoscientists** [(short course in 2022/09 at University of Calgary, Department of Geoscience, Calgary, AB, Canada)]{style="color:grey"}
